# Twitter/X Analytics — Data Analysis

## Business Objective

To analyze Twitter/X performance data and provide actionable insights into:
- Reach and impressions
- Engagement performance
- Content performance
- Media and interaction effectiveness
- Hashtags and mentions
- Time-based performance patterns

The analysis aims to help marketing teams understand what content performs well and identify patterns that can support future content planning.

## Import Libraries & Load Dataset ##

In [5]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd

data = pd.read_excel("../data/raw/Tweet.xlsx")
data.head()

,Tweet,id,time,impressions,engagements,engagement rate,retweets,replies,likes,user profile clicks,...,hashtag clicks,detail expands,permalink clicks,app opens,app installs,follows,email tweet,dial phone,media views,media engagements
0,id ligula suspendisse ornare consequat lectus ...,6672567125560790,2020-06-30 21:09 +0000,365.0,4.0,0.010959,0.0,0,1.0,2.0,...,0,1,0,0,0,0,0,0,0.0,0.0
1,euismod scelerisque quam turpis adipiscing lor...,8265456713789040,2020-06-30 17:14 +0000,184.0,2.0,0.010870,0.0,0,2.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
2,leo rhoncus sed vestibulum sit amet cursus id ...,281117346800427,2020-06-30 16:59 +0000,2644.0,46.0,0.017398,1.0,1,17.0,0.0,...,0,23,0,0,0,0,0,0,354.0,1.0
3,aenean lectus pellentesque eget nunc donec qui...,7758025943576750,2020-06-30 13:55 +0000,301.0,3.0,0.009967,0.0,1,2.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
4,sed accumsan felis ut at dolor quis odio conse...,6131837006729570,2020-06-30 12:13 +0000,528.0,0.0,0.000000,0.0,0,0.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0

In [7]:
df=data.copy()

## Data Overview ##

In [8]:
print("Row: ",df.shape[0])
print("Column: ",df.shape[1])

Row:  1181
Column:  21

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1181 entries, 0 to 1180
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Tweet                1181 non-null   str
 1   id                   1181 non-null   int64
 2   time                 1181 non-null   object
 3   impressions          1179 non-null   float64
 4   engagements          1179 non-null   float64
 5   engagement rate      1179 non-null   float64
 6   retweets             1180 non-null   float64
 7   replies              1181 non-null   int64
 8   likes                1181 non-null   float64
 9   user profile clicks  1181 non-null   float64
 10  url clicks           1181 non-null   int64
 11  hashtag clicks       1181 non-null   int64
 12  detail expands       1181 non-null   int64
 13  permalink clicks     1181 non-null   int64
 14  app opens            1181 non-null   int64
 15  app installs         1181 non-null   int64
 16  follows              1181 non-null   int64
 17  email tweet          1181 non-null   int64
 18  dial phone           1181 non-null   int64
 19  media views          1169 non-null   float64
 20  media engagements    1168 non-null   float64
dtypes: float64(8), int64(11), object(1), str(1)
memory usage: 193.9+ KB

In [10]:
df.describe()

,id,impressions,engagements,engagement rate,retweets,replies,likes,user profile clicks,url clicks,hashtag clicks,detail expands,permalink clicks,app opens,app installs,follows,email tweet,dial phone,media views,media engagements
count,1.181000e+03,1179.000000,1179.000000,1179.000000,1180.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.0,1181.000000,1181.000000,1169.000000,1168.000000
mean,4.869653e+15,773.282124,78.285838,0.066514,0.937288,1.417443,6.932271,2.176127,3.022862,0.259949,13.128704,0.000847,0.002540,0.000847,0.0,1.738357,0.462320,76.197605,52.671233
std,2.912818e+15,4679.852991,1578.955143,0.534397,12.906901,14.395244,72.879727,20.382764,19.655602,1.610662,136.196470,0.029099,0.065045,0.029099,0.0,41.171964,11.438397,1363.459588,1361.448226
min,4.837987e+12,0.010899,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
25%,2.345457e+15,163.000000,3.000000,0.012206,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
50%,4.789145e+15,295.000000,6.000000,0.023392,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
75%,7.465578e+15,704.000000,18.000000,0.043011,0.000000,1.000000,5.000000,1.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,30.000000,1.000000
max,9.987611e+15,156685.000000,54098.000000,15.000000,402.000000,483.000000,2487.000000,641.000000,428.000000,41.000000,4024.000000,1.000000,2.000000,1.000000,0.0,1341.000000,381.000000,46489.000000,46489.000000

In [11]:
print("Total Records: ",len(df))
print("Unique Tweets IDs:", df["Tweet"].nunique())
print("Duplicate IDs:", df["id"].duplicated().sum())

Total Records:  1181
Unique Tweets IDs: 1181
Duplicate IDs: 0

In [12]:
df["time"] = pd.to_datetime(
    df["time"],
    format="%Y-%m-%d %H:%M %z",
    errors="coerce"
)
df["time"].dtype

datetime64[us, UTC]

In [13]:
print("Start Date:", df["time"].min())
print("End Date:", df["time"].max())

Start Date: 2020-06-01 00:34:00+00:00
End Date: 2020-10-19 13:14:00+00:00

## Numerical Summary ##

In [14]:
metrics = [
    "impressions",
    "engagements",
    "engagement rate",
    "retweets",
    "replies",
    "likes",
    "user profile clicks",
    "url clicks",
    "hashtag clicks",
    "detail expands",
    "permalink clicks",
    "app opens",
    "app installs",
    "follows",
    "email tweet",
    "dial phone",
    "media views",
    "media engagements"
]

summary = df[metrics].agg(["sum", "mean", "median", "min", "max"]).T

summary

                               sum        mean      median       min       max
impressions          911699.623972  773.282124  295.000000  0.010899  156685.0
engagements           92299.002469   78.285838    6.000000  0.000000   54098.0
engagement rate          78.419426    0.066514    0.023392  0.000000      15.0
retweets               1106.000000    0.937288    0.000000  0.000000     402.0
replies                1674.000000    1.417443    0.000000  0.000000     483.0
likes                  8187.012438    6.932271    2.000000  0.000000    2487.0
user profile clicks    2570.006211    2.176127    0.000000  0.000000     641.0
url clicks             3570.000000    3.022862    0.000000  0.000000     428.0
hashtag clicks          307.000000    0.259949    0.000000  0.000000      41.0
detail expands        15505.000000   13.128704    2.000000  0.000000    4024.0
permalink clicks          1.000000    0.000847    0.000000  0.000000       1.0
app opens                 3.000000    0.002540    0.000000  0.000000       2.0
app installs              1.000000    0.000847    0.000000  0.000000       1.0
follows                   0.000000    0.000000    0.000000  0.000000       0.0
email tweet            2053.000000    1.738357    0.000000  0.000000    1341.0
dial phone              546.000000    0.462320    0.000000  0.000000     381.0
media views           89075.000000   76.197605    0.000000  0.000000   46489.0
media engagements     61520.000000   52.671233    0.000000  0.000000   46489.0

## Data quality checks ##

In [15]:
missing_values=df.isnull().sum()
duplicated_records=df.duplicated().sum()
datatypes=df.dtypes
TotalRecords=df.shape
print(f"Missing values:\n{missing_values}\n\nDuplicate rows: {duplicated_records}\n\nData types:\n{datatypes}\n\nTotal records: {TotalRecords}")

Missing values:
Tweet                   0
id                      0
time                   15
impressions             2
engagements             2
engagement rate         2
retweets                1
replies                 0
likes                   0
user profile clicks     0
url clicks              0
hashtag clicks          0
detail expands          0
permalink clicks        0
app opens               0
app installs            0
follows                 0
email tweet             0
dial phone              0
media views            12
media engagements      13
dtype: int64

Duplicate rows: 0

Data types:
Tweet                                  str
id                                   int64
time                   datetime64[us, UTC]
impressions                        float64
engagements                        float64
engagement rate                    float64
retweets                           float64
replies                              int64
likes                              float64
user profile clicks                float64
url clicks                           int64
hashtag clicks                       int64
detail expands                       int64
permalink clicks                     int64
app opens                            int64
app installs                         int64
follows                              int64
email tweet                          int64
dial phone                           int64
media views                        float64
media engagements                  float64
dtype: object

Total records: (1181, 21)

## Data Cleaning ##

In [16]:
df[df.isnull().any(axis=1)]

# time columns has integer and categorical values that is not correct and became a reason for further investigation. I will
#  convert the time column to datetime format and check for any missing values.

,Tweet,id,time,impressions,engagements,engagement rate,retweets,replies,likes,user profile clicks,...,hashtag clicks,detail expands,permalink clicks,app opens,app installs,follows,email tweet,dial phone,media views,media engagements
105,vestibulum rutrum rutrum neque aenean auctor g...,888700741172246,NaT,0.061340,16.000000,15.0,49.0,12,114.000000,0.000000,...,0,0,0,0,0,0,1341,29,NaN,NaN
332,ridiculus mus etiam vel augue vestibulum rutru...,9697973160692210,NaT,0.050398,9.000000,0.0,15.0,4,6.000000,0.000000,...,0,1,1,0,0,0,16,16,NaN,NaN
338,in porttitor pede justo eu massa donec dapibus...,5342046410774140,NaT,0.058455,0.000000,2.0,12.0,1,0.000000,1.000000,...,0,0,0,0,0,0,0,0,NaN,NaN
364,eget tempus vel pede morbi porttitor lorem id ...,222273100384546,NaT,0.060484,0.000000,1.0,18.0,4,0.000000,0.000000,...,0,0,0,0,0,0,0,0,NaN,NaN
376,in tempus sit amet sem fusce consequat nulla n...,5648246278088280,NaT,0.081575,3.000000,9.0,40.0,15,0.000000,0.000000,...,0,0,0,0,0,0,0,0,NaN,NaN
414,mauris eget massa tempor convallis nulla neque...,5307404572357200,NaT,NaN,NaN,NaN,402.0,5,0.012438,0.000000,...,3,0,0,0,1,0,0,0,0.0,0.0
514,in libero ut massa volutpat convallis morbi od...,3090923817145680,NaT,NaN,NaN,NaN,NaN,483,3.000000,0.006211,...,0,3,0,0,0,0,0,0,0.0,0.0
547,semper est quam pharetra magna ac consequat me...,4705453955691760,NaT,0.011494,0.000000,0.0,1.0,2,0.000000,0.000000,...,0,0,0,0,0,0,0,0,NaN,NaN
563,sollicitudin ut suscipit a feugiat et eros ves...,8848450490428020,NaT,0.010899,0.000000,0.0,3.0,1,0.000000,0.000000,...,0,0,0,0,0,0,0,0,NaN,NaN
711,etiam vel augue vestibulum rutrum rutrum neque...,6165418458991460,NaT,0.024590,1.000000,1.0,1.0,0,0.000000,0.000000,...,0,0,0,0,0,0,0,0,NaN,NaN
786,magna vulputate luctus cum sociis natoque pena...,9872118355006670,NaT,0.048144,8.000000,1.0,22.0,10,97.000000,0.000000,...,0,0,0,0,0,0,85,85,NaN,NaN
848,nulla ultrices aliquet maecenas leo odio condi...,2886472383828430,NaT,1.000000,0.002469,0.0,0.0,0,0.000000,0.000000,...,1,0,0,0,0,0,0,34,0.0,NaN
1002,sodales scelerisque mauris sit amet eros suspe...,4429373758549880,NaT,0.136460,12.000000,4.0,41.0,9,37.000000,0.000000,...,0,0,0,0,0,0,381,381,NaN,NaN
1039,at ipsum ac tellus semper interdum mauris ulla...,4890803324822480,NaT,0.050360,0.000000,3.0,16.0,0,29.000000,0.000000,...,0,0,0,0,0,0,0,0,NaN,NaN
1092,elit proin interdum mauris non ligula pellente...,2143383459395710,NaT,0.029773,6.000000,0.0,15.0,1,18.000000,1.000000,...,0,0,0,0,0,0,230,1,NaN,NaN

In [17]:
print("Invalid timestamps:", df["time"].isna().sum())
print("Invalid records :",df.loc[df["time"].isna()])

# 15 records with invalid timestamps were removed because the time field could not be parsed into a valid datetime, making 
# them unsuitable for time-based analysis.

Invalid timestamps: 15
Invalid records :                                                   Tweet                id  \
105   vestibulum rutrum rutrum neque aenean auctor g...   888700741172246
332   ridiculus mus etiam vel augue vestibulum rutru...  9697973160692210
338   in porttitor pede justo eu massa donec dapibus...  5342046410774140
364   eget tempus vel pede morbi porttitor lorem id ...   222273100384546
376   in tempus sit amet sem fusce consequat nulla n...  5648246278088280
414   mauris eget massa tempor convallis nulla neque...  5307404572357200
514   in libero ut massa volutpat convallis morbi od...  3090923817145680
547   semper est quam pharetra magna ac consequat me...  4705453955691760
563   sollicitudin ut suscipit a feugiat et eros ves...  8848450490428020
711   etiam vel augue vestibulum rutrum rutrum neque...  6165418458991460
786   magna vulputate luctus cum sociis natoque pena...  9872118355006670
848   nulla ultrices aliquet maecenas leo odio condi...  2886472383828430
1002  sodales scelerisque mauris sit amet eros suspe...  4429373758549880
1039  at ipsum ac tellus semper interdum mauris ulla...  4890803324822480
1092  elit proin interdum mauris non ligula pellente...  2143383459395710

     time  impressions  engagements  engagement rate  retweets  replies  \
105   NaT     0.061340    16.000000             15.0      49.0       12
332   NaT     0.050398     9.000000              0.0      15.0        4
338   NaT     0.058455     0.000000              2.0      12.0        1
364   NaT     0.060484     0.000000              1.0      18.0        4
376   NaT     0.081575     3.000000              9.0      40.0       15
414   NaT          NaN          NaN              NaN     402.0        5
514   NaT          NaN          NaN              NaN       NaN      483
547   NaT     0.011494     0.000000              0.0       1.0        2
563   NaT     0.010899     0.000000              0.0       3.0        1
711   NaT     0.024590     1.000000              1.0       1.0        0
786   NaT     0.048144     8.000000              1.0      22.0       10
848   NaT     1.000000     0.002469              0.0       0.0        0
1002  NaT     0.136460    12.000000              4.0      41.0        9
1039  NaT     0.050360     0.000000              3.0      16.0        0
1092  NaT     0.029773     6.000000              0.0      15.0        1

           likes  user profile clicks  ...  hashtag clicks  detail expands  \
105   114.000000             0.000000  ...               0               0
332     6.000000             0.000000  ...               0               1
338     0.000000             1.000000  ...               0               0
364     0.000000             0.000000  ...               0               0
376     0.000000             0.000000  ...               0               0
414     0.012438             0.000000  ...               3               0
514     3.000000             0.006211  ...               0               3
547     0.000000             0.000000  ...               0               0
563     0.000000             0.000000  ...               0               0
711     0.000000             0.000000  ...               0               0
786    97.000000             0.000000  ...               0               0
848     0.000000             0.000000  ...               1               0
1002   37.000000             0.000000  ...               0               0
1039   29.000000             0.000000  ...               0               0
1092   18.000000             1.000000  ...               0               0

      permalink clicks  app opens  app installs  follows  email tweet  \
105                  0          0             0        0         1341
332                  1          0             0        0           16
338                  0          0             0        0            0
364                  0          0             0        0            0
376                  0          0             0        0            0
414                  0          0             1        0            0
514                  0          0             0        0            0
547                  0          0             0        0            0
563                  0          0             0        0            0
711                  0          0             0        0            0
786                  0          0             0        0           85
848                  0          0             0        0            0
1002                 0          0             0        0          381
1039                 0          0             0        0            0
1092                 0          0             0        0          230

      dial phone  media views  media engagements
105           29          NaN                NaN
332           16          NaN                NaN
338            0          NaN                NaN
364            0          NaN                NaN
376            0          NaN                NaN
414            0          0.0                0.0
514            0          0.0                0.0
547            0          NaN                NaN
563            0          NaN                NaN
711            0          NaN                NaN
786           85          NaN                NaN
848           34          0.0                NaN
1002         381          NaN                NaN
1039           0          NaN                NaN
1092           1          NaN                NaN

[15 rows x 21 columns]

In [18]:
df=df.dropna(subset=["time"]).copy()

In [19]:
print("Remaining rows:", len(df))
print("Missing timestamps:", df["time"].isna().sum())

Remaining rows: 1166
Missing timestamps: 0

In [20]:
print(df.isnull().sum())

Tweet                  0
id                     0
time                   0
impressions            0
engagements            0
engagement rate        0
retweets               0
replies                0
likes                  0
user profile clicks    0
url clicks             0
hashtag clicks         0
detail expands         0
permalink clicks       0
app opens              0
app installs           0
follows                0
email tweet            0
dial phone             0
media views            0
media engagements      0
dtype: int64

In [21]:
columns_to_drop = [
    "detail expands",
    "permalink clicks",
    "app opens",
    "app installs",
    "follows",
    "email tweet",
    "dial phone"
]

df.drop(columns=columns_to_drop, inplace=True)

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 1166 entries, 0 to 1180
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Tweet                1166 non-null   str
 1   id                   1166 non-null   int64
 2   time                 1166 non-null   datetime64[us, UTC]
 3   impressions          1166 non-null   float64
 4   engagements          1166 non-null   float64
 5   engagement rate      1166 non-null   float64
 6   retweets             1166 non-null   float64
 7   replies              1166 non-null   int64
 8   likes                1166 non-null   float64
 9   user profile clicks  1166 non-null   float64
 10  url clicks           1166 non-null   int64
 11  hashtag clicks       1166 non-null   int64
 12  media views          1166 non-null   float64
 13  media engagements    1166 non-null   float64
dtypes: datetime64[us, UTC](1), float64(8), int64(4), str(1)
memory usage: 136.6 KB

## Top-Performing Tweet Analysis ##

In [23]:
top_impressions=df.nlargest(10,"impressions")[["Tweet","id","time","impressions","engagements","engagement rate"]]
top_impressions

,Tweet,id,time,impressions,engagements,engagement rate
441,elementum ligula vehicula consequat morbi a ip...,5786474615304760,2020-07-10 13:47:00+00:00,156685.0,54098.0,0.345266
880,sit amet lobortis sapien sapien non mi integer...,2371155986192380,2020-09-16 19:34:00+00:00,18501.0,2274.0,0.122912
67,nulla neque libero convallis eget eleifend luc...,3651418391136910,2020-06-26 20:03:00+00:00,11496.0,1065.0,0.092641
541,justo in hac habitasse platea dictumst etiam f...,1913619913870820,2020-07-01 00:25:00+00:00,9820.0,1553.0,0.158147
623,accumsan felis ut at dolor quis odio consequat...,9776744833976440,2020-08-19 17:32:00+00:00,9743.0,317.0,0.032536
778,morbi sem mauris laoreet ut rhoncus aliquet pu...,4619420122428250,2020-09-30 01:53:00+00:00,8095.0,924.0,0.114145
1139,nam dui proin leo odio porttitor id consequat ...,1899240801211820,2020-10-06 10:28:00+00:00,7435.0,919.0,0.123605
749,lectus aliquam sit amet diam in magna bibendum...,6061425928024140,2020-08-03 12:52:00+00:00,6807.0,1118.0,0.164243
497,augue quam sollicitudin vitae consectetuer ege...,4443858600767830,2020-07-06 01:37:00+00:00,6726.0,1191.0,0.177074
843,tortor risus dapibus augue vel accumsan tellus...,2653935583674500,2020-09-22 14:38:00+00:00,5972.0,307.0,0.051407

In [24]:
top_engagements=df.nlargest(10,"engagements")[["Tweet","id","time","impressions","engagements","engagement rate"]]
top_engagements

,Tweet,id,time,impressions,engagements,engagement rate
441,elementum ligula vehicula consequat morbi a ip...,5786474615304760,2020-07-10 13:47:00+00:00,156685.0,54098.0,0.345266
880,sit amet lobortis sapien sapien non mi integer...,2371155986192380,2020-09-16 19:34:00+00:00,18501.0,2274.0,0.122912
541,justo in hac habitasse platea dictumst etiam f...,1913619913870820,2020-07-01 00:25:00+00:00,9820.0,1553.0,0.158147
497,augue quam sollicitudin vitae consectetuer ege...,4443858600767830,2020-07-06 01:37:00+00:00,6726.0,1191.0,0.177074
749,lectus aliquam sit amet diam in magna bibendum...,6061425928024140,2020-08-03 12:52:00+00:00,6807.0,1118.0,0.164243
67,nulla neque libero convallis eget eleifend luc...,3651418391136910,2020-06-26 20:03:00+00:00,11496.0,1065.0,0.092641
778,morbi sem mauris laoreet ut rhoncus aliquet pu...,4619420122428250,2020-09-30 01:53:00+00:00,8095.0,924.0,0.114145
1139,nam dui proin leo odio porttitor id consequat ...,1899240801211820,2020-10-06 10:28:00+00:00,7435.0,919.0,0.123605
430,arcu sed augue aliquam erat volutpat in congue...,4081525895159210,2020-07-10 23:00:00+00:00,2184.0,533.0,0.244048
434,semper porta volutpat quam pede lobortis ligul...,2194519685281400,2020-07-10 18:40:00+00:00,3727.0,486.0,0.130400

In [25]:
top_engagement_rate=df.nlargest(10,"engagement rate")[["Tweet","id","time","impressions","engagements","engagement rate"]]
top_engagement_rate

,Tweet,id,time,impressions,engagements,engagement rate
148,amet sem fusce consequat nulla nisl nunc nisl ...,5282614437910190,2020-06-17 17:39:00+00:00,277.0,108.0,0.389892
1138,nibh in hac habitasse platea dictumst aliquam ...,1545885402365220,2020-10-06 10:32:00+00:00,1271.0,463.0,0.364280
441,elementum ligula vehicula consequat morbi a ip...,5786474615304760,2020-07-10 13:47:00+00:00,156685.0,54098.0,0.345266
421,sapien urna pretium nisl ut volutpat sapien ar...,3387356756452090,2020-07-12 01:33:00+00:00,299.0,84.0,0.280936
451,ac neque duis bibendum morbi non quam nec dui ...,708969332489629,2020-07-09 19:21:00+00:00,734.0,206.0,0.280654
907,morbi non lectus aliquam sit amet diam in magn...,8767385170248200,2020-09-13 00:23:00+00:00,35.0,9.0,0.257143
430,arcu sed augue aliquam erat volutpat in congue...,4081525895159210,2020-07-10 23:00:00+00:00,2184.0,533.0,0.244048
845,augue vestibulum rutrum rutrum neque aenean au...,9569375292681000,2020-09-21 20:16:00+00:00,377.0,92.0,0.244032
66,nulla sed accumsan felis ut at dolor quis odio...,6888512031913890,2020-06-26 20:59:00+00:00,866.0,194.0,0.224018
989,ultrices posuere cubilia curae donec pharetra ...,2525599018726140,2020-09-01 17:01:00+00:00,1101.0,231.0,0.209809

In [26]:
engagement_columns = [
    "likes",
    "retweets",
    "replies",
    "user profile clicks",
    "url clicks",
    "hashtag clicks"
]

engagement_summary = pd.DataFrame({
    "Total": df[engagement_columns].sum(),
    "Average": df[engagement_columns].mean(),
    "Median": df[engagement_columns].median()
})

engagement_summary

                      Total   Average  Median
likes                7883.0  6.760720     2.0
retweets              471.0  0.403945     0.0
replies              1127.0  0.966552     0.0
user profile clicks  2568.0  2.202401     0.0
url clicks           2829.0  2.426244     0.0
hashtag clicks        303.0  0.259863     0.0

## Creating Time Features ##

In [27]:
df["date"] = df["time"].dt.date
df["year"] = df["time"].dt.year
df["month"] = df["time"].dt.month
df["month_name"] = df["time"].dt.month_name()
df["day"] = df["time"].dt.day
df["day_of_week"] = df["time"].dt.day_name()
df["hour"] = df["time"].dt.hour
df.head(10)

,Tweet,id,time,impressions,engagements,engagement rate,retweets,replies,likes,user profile clicks,...,hashtag clicks,media views,media engagements,date,year,month,month_name,day,day_of_week,hour
0,id ligula suspendisse ornare consequat lectus ...,6672567125560790,2020-06-30 21:09:00+00:00,365.0,4.0,0.010959,0.0,0,1.0,2.0,...,0,0.0,0.0,2020-06-30,2020,6,June,30,Tuesday,21
1,euismod scelerisque quam turpis adipiscing lor...,8265456713789040,2020-06-30 17:14:00+00:00,184.0,2.0,0.010870,0.0,0,2.0,0.0,...,0,0.0,0.0,2020-06-30,2020,6,June,30,Tuesday,17
2,leo rhoncus sed vestibulum sit amet cursus id ...,281117346800427,2020-06-30 16:59:00+00:00,2644.0,46.0,0.017398,1.0,1,17.0,0.0,...,0,354.0,1.0,2020-06-30,2020,6,June,30,Tuesday,16
3,aenean lectus pellentesque eget nunc donec qui...,7758025943576750,2020-06-30 13:55:00+00:00,301.0,3.0,0.009967,0.0,1,2.0,0.0,...,0,0.0,0.0,2020-06-30,2020,6,June,30,Tuesday,13
4,sed accumsan felis ut at dolor quis odio conse...,6131837006729570,2020-06-30 12:13:00+00:00,528.0,0.0,0.000000,0.0,0,0.0,0.0,...,0,0.0,0.0,2020-06-30,2020,6,June,30,Tuesday,12
5,consequat metus sapien ut nunc vestibulum ante...,7158204930285070,2020-06-30 12:06:00+00:00,962.0,37.0,0.038462,0.0,2,7.0,6.0,...,3,0.0,0.0,2020-06-30,2020,6,June,30,Tuesday,12
6,morbi odio odio elementum eu interdum eu tinci...,8412656725709000,2020-06-30 11:29:00+00:00,198.0,4.0,0.020202,0.0,0,1.0,1.0,...,0,0.0,0.0,2020-06-30,2020,6,June,30,Tuesday,11
7,eget massa tempor convallis nulla neque libero...,1697739445805240,2020-06-30 11:20:00+00:00,1298.0,28.0,0.021572,0.0,2,3.0,0.0,...,3,0.0,0.0,2020-06-30,2020,6,June,30,Tuesday,11
8,tempus sit amet sem fusce consequat nulla nisl...,5739997848071200,2020-06-30 11:04:00+00:00,160.0,3.0,0.018750,0.0,1,1.0,0.0,...,0,27.0,0.0,2020-06-30,2020,6,June,30,Tuesday,11
9,ultrices erat tortor sollicitudin mi sit amet ...,7941923809016870,2020-06-30 11:01:00+00:00,1080.0,25.0,0.023148,0.0,2,7.0,0.0,...,2,191.0,3.0,2020-06-30,2020,6,June,30,Tuesday,11

## Calculate Interactions ##

In [28]:
interaction_cols = [
    "likes",
    "retweets",
    "replies",
    "user profile clicks",
    "url clicks",
    "hashtag clicks"
]

df["calculated_interactions"] = df[interaction_cols].sum(axis=1)

df[[
    "engagements",
    "calculated_interactions"
]].head(20)

    engagements  calculated_interactions
0           4.0                      3.0
1           2.0                      2.0
2          46.0                     22.0
3           3.0                      3.0
4           0.0                      0.0
5          37.0                     18.0
6           4.0                      2.0
7          28.0                      8.0
8           3.0                      2.0
9          25.0                     13.0
10         19.0                      2.0
11          5.0                      3.0
12          2.0                      2.0
13          7.0                      1.0
14         16.0                     12.0
15          4.0                      4.0
16         65.0                     28.0
17          2.0                      1.0
18          1.0                      1.0
19          0.0                      0.0

## Engagement Difference ##

In [29]:
difference = (
    df["engagements"] - df["calculated_interactions"]
)
print(difference.describe())

df["interaction_difference"]=difference

df.nlargest(
    10,
    "interaction_difference"
)[[
    "Tweet",
    "time",
    "engagements",
    "calculated_interactions",
    "interaction_difference"
]]

count     1166.000000
mean        66.091767
std       1482.368484
min          0.000000
25%          0.000000
50%          2.000000
75%          8.000000
max      50513.000000
dtype: float64

,Tweet,time,engagements,calculated_interactions,interaction_difference
441,elementum ligula vehicula consequat morbi a ip...,2020-07-10 13:47:00+00:00,54098.0,3585.0,50513.0
880,sit amet lobortis sapien sapien non mi integer...,2020-09-16 19:34:00+00:00,2274.0,125.0,2149.0
541,justo in hac habitasse platea dictumst etiam f...,2020-07-01 00:25:00+00:00,1553.0,154.0,1399.0
497,augue quam sollicitudin vitae consectetuer ege...,2020-07-06 01:37:00+00:00,1191.0,67.0,1124.0
749,lectus aliquam sit amet diam in magna bibendum...,2020-08-03 12:52:00+00:00,1118.0,94.0,1024.0
67,nulla neque libero convallis eget eleifend luc...,2020-06-26 20:03:00+00:00,1065.0,89.0,976.0
1139,nam dui proin leo odio porttitor id consequat ...,2020-10-06 10:28:00+00:00,919.0,95.0,824.0
778,morbi sem mauris laoreet ut rhoncus aliquet pu...,2020-09-30 01:53:00+00:00,924.0,156.0,768.0
1138,nibh in hac habitasse platea dictumst aliquam ...,2020-10-06 10:32:00+00:00,463.0,3.0,460.0
430,arcu sed augue aliquam erat volutpat in congue...,2020-07-10 23:00:00+00:00,533.0,96.0,437.0

## Overall Twitter Performance ##

In [30]:
summary = {
    "Total Tweets": len(df),
    "Total Impressions": df["impressions"].sum(),
    "Total Engagements": df["engagements"].sum(),
    "Average Impressions": df["impressions"].mean(),
    "Average Engagements": df["engagements"].mean(),
    "Average Engagement Rate": df["engagement rate"].mean(),
    "Median Impressions": df["impressions"].median(),
    "Median Engagements": df["engagements"].median(),
    "Median Engagement Rate": df["engagement rate"].median()
}

summary

{'Total Tweets': 1166,
 'Total Impressions': np.float64(911698.0),
 'Total Engagements': np.float64(92244.0),
 'Average Impressions': np.float64(781.902229845626),
 'Average Engagements': np.float64(79.1114922813036),
 'Average Engagement Rate': np.float64(0.03638029681132075),
 'Median Impressions': np.float64(298.5),
 'Median Engagements': np.float64(6.0),
 'Median Engagement Rate': np.float64(0.0232897145)}

In [31]:
df[[
    "impressions",
    "engagements",
    "engagement rate"
]].describe()

         impressions   engagements  engagement rate
count    1166.000000   1166.000000      1166.000000
mean      781.902230     79.111492         0.036380
std      4705.174635   1587.720740         0.042312
min         5.000000      0.000000         0.000000
25%       166.000000      3.000000         0.012247
50%       298.500000      6.000000         0.023290
75%       710.750000     18.000000         0.042003
max    156685.000000  54098.000000         0.389892

### Impressions Distribution ###

In [32]:
impression_bins = pd.cut(
    df["impressions"],
    bins=[0, 100, 500, 1000, 5000, 10000, float("inf")],
    labels=[
        "0–100",
        "101–500",
        "501–1K",
        "1K–5K",
        "5K–10K",
        "10K+"
    ]
)

impression_distribution = (
    impression_bins
    .value_counts()
    .sort_index()
)

impression_distribution

impressions
0–100      146
101–500    618
501–1K     210
1K–5K      179
5K–10K      10
10K+         3
Name: count, dtype: int64

### Engagement Distribution ###

In [33]:
engagement_bins = pd.cut(
    df["engagements"],
    bins=[-1, 5, 10, 25, 50, 100, 500, 1000, float("inf")],
    labels=[
        "0–5",
        "6–10",
        "11–25",
        "26–50",
        "51–100",
        "101–500",
        "501–1K",
        "1K+"
    ]
)

engagement_distribution = (
    engagement_bins
    .value_counts()
    .sort_index()
)

engagement_distribution

engagements
0–5        542
6–10       213
11–25      182
26–50       89
51–100      53
101–500     78
501–1K       3
1K+          6
Name: count, dtype: int64

### Interaction Summary ###

In [34]:
interaction_cols = [
    "likes",
    "retweets",
    "replies",
    "user profile clicks",
    "url clicks",
    "hashtag clicks"
]

interaction_summary = pd.DataFrame({
    "Total": df[interaction_cols].sum(),
    "Average": df[interaction_cols].mean(),
    "Median": df[interaction_cols].median()
})

interaction_summary["Percentage"] = (
    interaction_summary["Total"]
    / interaction_summary["Total"].sum()
    * 100
)

interaction_summary.sort_values(
    "Total",
    ascending=False
)

                      Total   Average  Median  Percentage
likes                7883.0  6.760720     2.0   51.926751
url clicks           2829.0  2.426244     0.0   18.635136
user profile clicks  2568.0  2.202401     0.0   16.915882
replies              1127.0  0.966552     0.0    7.423753
retweets              471.0  0.403945     0.0    3.102562
hashtag clicks        303.0  0.259863     0.0    1.995916

## Time Based Analysis ##

In [35]:
monthly_performance = (
    df.groupby("month_name", sort=False)
      .agg(
          tweets=("Tweet", "count"),
          impressions=("impressions", "sum"),
          engagements=("engagements", "sum"),
          avg_engagement_rate=("engagement rate", "mean")
      )
)

monthly_performance

            tweets  impressions  engagements  avg_engagement_rate
month_name
June           223     132703.0       5876.0             0.034560
July           312     353720.0      64880.0             0.036002
August         218     149361.0       7079.0             0.034673
September      232     175486.0       8820.0             0.038549
October        181     100428.0       5589.0             0.038552

In [36]:
day_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

day_performance = (
    df.groupby("day_of_week")
      .agg(
          tweets=("Tweet", "count"),
          impressions=("impressions", "sum"),
          engagements=("engagements", "sum"),
          avg_engagement_rate=("engagement rate", "mean")
      )
      .reindex(day_order)
)
day_performance["avg_impressions_per_tweet"] = (
day_performance["impressions"] / day_performance["tweets"]
)

day_performance["avg_engagements_per_tweet"] = (
day_performance["engagements"] / day_performance["tweets"]
)

day_performance

,tweets,impressions,engagements,avg_engagement_rate,avg_impressions_per_tweet,avg_engagements_per_tweet
day_of_week,,,,,,
Monday,187,143599.0,6983.0,0.032221,767.909091,37.342246
Tuesday,239,132672.0,6477.0,0.034411,555.112971,27.100418
Wednesday,215,160341.0,9986.0,0.035270,745.772093,46.446512
Thursday,230,116130.0,4465.0,0.037090,504.913043,19.413043
Friday,165,270250.0,60029.0,0.039027,1637.878788,363.812121
Saturday,50,36691.0,1522.0,0.032405,733.820000,30.440000
Sunday,80,52015.0,2782.0,0.049956,650.187500,34.775000

In [37]:
friday_tweets = df[df["day_of_week"] == "Friday"].copy()
friday_tweets[
    ["Tweet", "impressions", "engagements", "engagement rate"]
].sort_values(
    "engagements",
    ascending=False
).head(10)

,Tweet,impressions,engagements,engagement rate
441,elementum ligula vehicula consequat morbi a ip...,156685.0,54098.0,0.345266
67,nulla neque libero convallis eget eleifend luc...,11496.0,1065.0,0.092641
430,arcu sed augue aliquam erat volutpat in congue...,2184.0,533.0,0.244048
434,semper porta volutpat quam pede lobortis ligul...,3727.0,486.0,0.130400
227,sollicitudin ut suscipit a feugiat et eros ves...,5287.0,430.0,0.081332
288,felis ut at dolor quis odio consequat varius i...,3137.0,286.0,0.091170
66,nulla sed accumsan felis ut at dolor quis odio...,866.0,194.0,0.224018
1160,non mauris morbi non lectus aliquam sit amet d...,967.0,194.0,0.200620
436,justo sollicitudin ut suscipit a feugiat et er...,2930.0,171.0,0.058362
816,bibendum imperdiet nullam orci pede venenatis ...,3833.0,154.0,0.040177

In [38]:
hour_analysis = df.groupby("hour").agg(
    tweets=("id", "count"),
    impressions=("impressions", "sum"),
    engagements=("engagements", "sum"),
    avg_engagement_rate=("engagement rate", "mean"),
    median_engagement_rate=("engagement rate", "median")
).reset_index()

hour_analysis

,hour,tweets,impressions,engagements,avg_engagement_rate,median_engagement_rate
0,0,54,31609.0,2644.0,0.047686,0.029747
1,1,50,44528.0,3412.0,0.046988,0.028861
2,2,33,23322.0,1067.0,0.038395,0.022176
3,3,19,9598.0,489.0,0.046867,0.032680
4,4,6,1243.0,30.0,0.036475,0.031714
5,8,6,2493.0,94.0,0.036479,0.032561
6,9,11,4103.0,153.0,0.040824,0.023529
7,10,25,24398.0,1900.0,0.057970,0.025974
8,11,40,26852.0,1592.0,0.042735,0.024351
9,12,78,59738.0,2948.0,0.029790,0.020870
10,13,95,215083.0,56110.0,0.034796,0.023055
11,14,89,60110.0,2099.0,0.029749,0.019833
12,15,93,49728.0,1920.0,0.028622,0.020016
13,16,88,49995.0,1554.0,0.030914,0.023622
14,17,120,79318.0,3375.0,0.033285,0.020123
15,18,96,55953.0,2596.0,0.036386,0.022222
16,19,82,65196.0,4462.0,0.035658,0.023256
17,20,54,37576.0,2536.0,0.040988,0.022989
18,21,39,13952.0,446.0,0.037414,0.030864
19,22,47,27114.0,1173.0,0.037290,0.028571
20,23,41,29789.0,1644.0,0.043816,0.023419

In [39]:
day_hour_analysis = df.groupby(
    ["day_of_week", "hour"]
).agg(
    tweets=("id", "count"),
    impressions=("impressions", "sum"),
    engagements=("engagements", "sum"),
    avg_engagement_rate=("engagement rate", "mean"),
    median_engagement_rate=("engagement rate", "median")
).reset_index()

day_hour_analysis

,day_of_week,hour,tweets,impressions,engagements,avg_engagement_rate,median_engagement_rate
0,Friday,0,7,5768.0,155.0,0.042931,0.020301
1,Friday,1,9,2699.0,92.0,0.031123,0.019417
2,Friday,2,7,3294.0,217.0,0.051115,0.039588
3,Friday,3,4,1398.0,204.0,0.071796,0.040730
4,Friday,4,1,56.0,5.0,0.089286,0.089286
...,...,...,...,...,...,...,...
126,Wednesday,19,15,26432.0,2462.0,0.023983,0.021203
127,Wednesday,20,11,4050.0,188.0,0.029817,0.025641
128,Wednesday,21,4,1057.0,20.0,0.032229,0.031426
129,Wednesday,22,5,1806.0,20.0,0.014363,0.014528
130,Wednesday,23,9,4745.0,363.0,0.055983,0.039604

## Relationship & Correlation Analysis ##

In [40]:
df[[
    "impressions",
    "engagements",
    "engagement rate"
]].corr()

                 impressions  engagements  engagement rate
impressions         1.000000     0.983443         0.254709
engagements         0.983443     1.000000         0.244017
engagement rate     0.254709     0.244017         1.000000

In [41]:
df[[
    "impressions",
    "engagements",
    "engagement rate"
]].corr(method="spearman")

                 impressions  engagements  engagement rate
impressions         1.000000     0.722908         0.063409
engagements         0.722908     1.000000         0.672029
engagement rate     0.063409     0.672029         1.000000

## Impression Quartile vs Engagement Rate ##

In [42]:
df.groupby(
    pd.qcut(df["impressions"], 4)
)["engagement rate"].agg(
    ["count", "mean", "median"]
)

                    count      mean    median
impressions
(4.999, 166.0]        295  0.037681  0.027027
(166.0, 298.5]        288  0.029131  0.020182
(298.5, 710.75]       291  0.026509  0.017964
(710.75, 156685.0]    292  0.052054  0.031535

## Save Cleaned Dataset ##

In [43]:
Clean_twitter=df.to_csv(
    "../data/processed/twitter_analysis_cleaned.csv",
    index=False
)

# Key Business Insights

## 1. Reach & Visibility
Analyze the overall impression volume and distribution of tweet reach.

## 2. Engagement
Identify the major interaction types and overall engagement behavior.

## 3. Content Performance
Identify tweets that generate high impressions, high engagements, and high engagement rates.

## 4. Timing
Analyze monthly, day-of-week, hourly, and day-hour performance patterns.

## 5. Engagement Relationships
Evaluate the relationship between impressions, engagements, and engagement rate using Pearson and Spearman correlation.

## 6. Content Planning Opportunities
Use the observed performance patterns to support future Twitter/X content planning and campaign monitoring.